module.exports = {
  mktNameToWebPortalOrgDirNameMapping: {
    // 'SCBS Investment Account': 'scbs',
    // FinNet: 'finnet',
    // KBANK: 'kbank',
    // 'Asia Plus Securities Company Limited': 'asps',
    // KBANK: 'kbank',
    // ONEAM: 'oneam',
    // 'Siam Commercial Bank (SCB)': 'scb',
    // Kasikorn_Securities_PCL: 'ksec',
    // 'Krungthai Bank': 'ktb',
    // 'CIMB THAI Bank': 'cimb',
    // 'DBS Vickers Securities(Thailand) Co., Ltd.': 'dbs',
    // 'Mizuho Bank': 'mhcb',
    // KKP: 'kkp',
    // 'Thanachart Bank': 'tbank',
    // 'Bangkok Bank': 'bbl',
    // 'Bank of Ayudhya Public Company Limited': 'bay',
    // 'TMB Bank PCL.': 'tmb',
    ASPS: 'asps',
    KRUNGSRI: 'bay',
    BBL: 'bbl',
    CITI: 'citi',
    'KASIKORN BANK': 'kbank',
    KTB: 'ktb',
    TMB: 'tmb',
    UOB: 'uob',
    GSB: 'gsb',
    NCB: 'ncb',
    MHCB: 'mhcb',
    SCB: 'scb',
    KKB: 'kkb',
    CIMB: 'cimb',
    TBANK: 'tbank',
    NDIDMOCK: 'ndidmock',
  },
};
