version: '3'
services:
  settlement-report:
    image: prapatb/ndid-settlement-report:latest
    environment: 
      - TM_RPC_IP=${TM_RPC_IP:-127.0.0.1}
      - TM_RPC_PORT=${TM_RPC_PORT:-26000}
      - QUERY_SETTLEMENT=${QUERY_SETTLEMENT:-YES}
      - MIN_BLOCK_HEIGHT=${MIN_BLOCK_HEIGHT}
      - MAX_BLOCK_HEIGHT=${MAX_BLOCK_HEIGHT}
      - START_BLOCK=${MIN_BLOCK_HEIGHT}
      - END_BLOCK=${MIN_BLOCK_HEIGHT}
      - DEBUG_FILE=${DEBUG_FILE}
      - EXEC_DATETIME=${DATETIME}
      - BILL_PERIOD_START=${BILL_PERIOD_START}
      - BILL_PERIOD_END=${BILL_PERIOD_END}
    security_opt:
      - no-new-privileges
    volumes:
      - ./settlement/${DATETIME:-result}/NodeInfo:/NodeInfo
      - ./settlement/${DATETIME:-result}/GetUsedTokenReport:/GetUsedTokenReport
      - ./settlement/${DATETIME:-result}/RequestDetail:/RequestDetail
      - ./settlement/${DATETIME:-result}/Reports:/Reports
      - ./settlement/Prices:/Prices
      - ${PENDING_REQS_PATH:-./settlement/pendingRequests.json}:/pendingRequests.json
    network_mode: "host"
