version: '3'
services:
  settlement-report:
    image: prapatb/ndid-settlement-report:1.2.2
    environment: 
      - TM_RPC_IP=${TM_RPC_IP:-127.0.0.1}
      - TM_RPC_PORT=${TM_RPC_PORT:-45000}
      - QUERY_SETTLEMENT=${QUERY_SETTLEMENT:-YES}
      - CHAIN_ID=${CHAIN_ID}
      - MIN_BLOCK_HEIGHT=${MIN_BLOCK_HEIGHT}
      - MAX_BLOCK_HEIGHT=${MAX_BLOCK_HEIGHT}
      - START_BLOCK=${MIN_BLOCK_HEIGHT}
      - END_BLOCK=${MAX_BLOCK_HEIGHT}
      - DEBUG_FILE=${DEBUG_FILE}
      - EXEC_DATETIME=${EXEC_DATETIME}
      - BILL_PERIOD_START=${BILL_PERIOD_START}
      - BILL_PERIOD_END=${BILL_PERIOD_END}
      - NDID_FEE=${NDID_FEE}
      - PORTAL_SUB_DIR=${PORTAL_SUB_DIR}
      - CREATE_LATEST=${CREATE_LATEST}
    security_opt:
      - no-new-privileges
    volumes:
      - ./settlement/${BILL_PERIOD_START}_${BILL_PERIOD_END}_${MIN_BLOCK_HEIGHT:-1}_${MAX_BLOCK_HEIGHT:-unlimit}_${EXEC_DATETIME}/NodeInfo:/NodeInfo
      - ./settlement/${BILL_PERIOD_START}_${BILL_PERIOD_END}_${MIN_BLOCK_HEIGHT:-1}_${MAX_BLOCK_HEIGHT:-unlimit}_${EXEC_DATETIME}/GetUsedTokenReport:/GetUsedTokenReport
      - ./settlement/${BILL_PERIOD_START}_${BILL_PERIOD_END}_${MIN_BLOCK_HEIGHT:-1}_${MAX_BLOCK_HEIGHT:-unlimit}_${EXEC_DATETIME}/RequestDetail:/RequestDetail
      - ./settlement/${BILL_PERIOD_START}_${BILL_PERIOD_END}_${MIN_BLOCK_HEIGHT:-1}_${MAX_BLOCK_HEIGHT:-unlimit}_${EXEC_DATETIME}/Reports:/Reports
      - ${PENDING_REQS_PATH:-./settlement/NextRound/pendingRequests.json}:/pendingRequests.json
      - ${WEB_PORTAL_DIR:-./settlement/WebPortal}:/WebPortal
      - ${PRICES_DIR:-./settlement/Prices}:/Prices
      - ${NEXT_ROUND_DIR:-./settlement/NextRound}:/NextRound
    network_mode: "host"
