version: '3'
services:
  settlement-report:
    image: prapatb/ndid-settlement-report:latest
    environment: 
      - TM_RPC_IP=${TM_RPC_IP:-127.0.0.1}
      - TM_RPC_PORT=${TM_RPC_PORT:-26000}
      - QUERY_SETTLEMENT=${QUERY_SETTLEMENT:-YES}
      - MIN_BLOCK_HEIGHT=${MIN_BLOCK_HEIGHT}
      - MAX_BLOCK_HEIGHT=${MAX_BLOCK_HEIGHT}
    security_opt:
      - no-new-privileges
    volumes:
      - ./settlement/GetUsedTokenReport:/GetUsedTokenReport
      - ./settlement/RequestDetail:/RequestDetail
      - ./settlement/Reports:/Reports
      - ./settlement/Prices:/Prices
    network_mode: "host"
